{% set name = "hepstats" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hepstats-{{ version }}.tar.gz
  sha256: 03dca8f63b00a0272a205ebf49dda412eede93c8e4bda711f8073c2343975e54

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm
  run:
    - asdf
    - numpy
    - pandas
    - python >=3.6
    - scipy
    - tqdm

test:
  imports:
    - hepstats
    - hepstats.hypotests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://scikit-hep.org/hepstats/
  summary: statistics tools and utilities
  license: BSD-3-Clause
  license_file:
    - LICENSES/LICENSE
    - LICENSES/LICENSE_ASTROML.rst
  dev_url: https://github.com/scikit-hep/hepstats
  doc_url: https://scikit-hep.org/hepstats/

extra:
  recipe-maintainers:
    - chrisburr
